project:
  type: website
  output-dir: docs
  
website:
  title: "CSUF_DS"
  navbar:
    left:
      - href: Project1.qmd
        text: Project1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



